---
- hosts: localhost
  connection: local
  gather_facts: no

  vars:
    delete_after_time: "10 minutes"

  tasks:
    - name: get all snapshots with specific tags
      ec2_snapshot_info:
        filters:
          "tag:System": SystemName
          "tag:Type":
            - db
            - app
      register: snapshots

    - name: get latest snapshot time
      set_fact:
        latest_ts_date: "{{ snapshots.snapshots | map(attribute='start_time') | max }}"

    - name: subtract threshold and format into time
      set_fact:
        adjusted_ts: "{{ lookup('pipe', \"date -u '+%Y-%m-%dT%H:%M:%S.%6N%:z' --date='\" + latest_ts_date + \" - \" + delete_after_time + \"' \")}}"


    - name: delete all snapshots older than "{{ latest_ts }}"
      ec2_snapshot:
        snapshot_id: "{{ item.snapshot_id }}"
        state: absent
        wait: no
      when: item.start_time < adjusted_ts
      with_items: "{{ snapshots.snapshots }}"
