---
- hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: get instances filtered on tags
      ec2_instance_facts:
        filters:
          "tag:Environment": Dev
          "tag:Platform": WJB
        validate_certs: no
      register: filtered_instances

    - name: add these instances to custom group
      add_host:
        name: "{{ item.private_ip_address }}"
        groups: a_group
        host_key_checking: no
      with_items: "{{ filtered_instances.instances }}"
