---
# - name: call script that has the following section in another file
#   import_playbook: ec2_groups.yml

- hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: get instances filtered on tags
      ec2_instance_facts:
        filters:
          "tag:Environment": Dev
          "tag:Platform": WJB
        validate_certs: no
      register: filtered_instances

    - name: add these instances to custom group
      add_host:
        name: "{{ item.private_ip_address }}"
        groups: a_group
      with_items: "{{ filtered_instances.instances }}"

- hosts: a_group
  remote_user: ec2-user
  become: yes
  gather_facts: no

  pre_tasks:
    - name: install python
      raw: 'sudo yum install -y python2'

  tasks:
    - name: update all packages on yum
      yum:
        name: '*'
        state: latest
